name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=https://github.com/nokx5/nokxpkgs/archive/main.tar.gz
      - run: nix-build -A golden_cpp
